services:
  db:
    image: mysql:8.0
    ports:
      - "4406:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=Airbnb_Taisei_development
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/Airbnb_Taisei
      - node_modules:/Airbnb_Taisei/node_modules
    ports:
      - "3002:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db

volumes:
  node_modules:
